name: Feature request
description: "Suggest an idea for this project"
labels: ["T-enhancement", "S-needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Is your feature request related to a problem? Please describe.
  - type: input
    attributes:
      label: "A clear and concise description of what the problem is."
      placeholder: "Ex: I'm always frustrated when [...]"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Describe the solution you'd like.
  - type: input
    attributes:
      label: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Describe alternatives you've considered.
  - type: textarea
    attributes:
      label: "A clear description of any alternative solutions or features you've considered."
      placeholder: |
        1. [...]
        2. [...]
        3. [...]
  - type: markdown
    attributes:
      value: |
        ## Additional context:
  - type: textarea
    attributes:
      label: "Add any other context or screenshots about the feature request here."
      
  
